name: Flybody
dname: fly_run
camera: 1
rendering_mjcf: ${paths.cwd_dir}/assets/fruitfly/fruitfly_force_fast.xml
stac_path: ${paths.data_dir}/transform_tethered.p
clip_idx: all_clips_batch_interp.p
env_args:
  clip_length: 1001
  mjcf_path: "${paths.cwd_dir}/assets/fruitfly/fruitfly_force_fast.xml" 
  physics_timestep: 2e-4
  solver: cg
  iterations: 8
  ls_iterations: 8
  torque_actuators: True
  physics_steps_per_control_step: 10
  too_far_dist: 0.01
  bad_pose_dist: 10.0
  pos_reward_weight: 1.0 
  tracking_lin_vel_weight: 0.0
  tracking_ang_vel_weight: 0.0
  lin_vel_z_weight: 0.0
  ang_vel_xy_weight: 0.0
  orientation_weight: 1.0
  torques_weight: 0.0
  action_rate_weight: 0.0
  stand_still_weight: 0.0
  foot_slip_weight: 0.0
  termination_weight: 1.0
  pos_scaling: 200.0
  linvel_scaling: 400.0
  angvel_scaling: 4.0
  ang_vel_xy_scaling: -1.0
  lin_vel_z_scaling: -1.0
  orientation_scaling: 5.0
  torques_scaling: -1.0
  action_rate_scaling: -1.0
  stand_still_scaling: -1.0
  foot_slip_scaling: -1.0
  healthy_z_range: [-0.03, 0.1]
  reset_noise_scale: 1e-3
  ref_len: 15
  free_jnt: True
  inference_mode: False
  end_eff_names:
    - claw_T1_left
    - claw_T1_right
    - claw_T2_left
    - claw_T2_right
    - claw_T3_left
    - claw_T3_right
  body_names:
    - coxa_T1_left
    - femur_T1_left
    - tibia_T1_left
    - tarsus_T1_left
    - tarsus2_T1_left
    - tarsus3_T1_left
    - tarsus4_T1_left
    - claw_T1_left
    - coxa_T1_right
    - femur_T1_right
    - tibia_T1_right
    - tarsus_T1_right
    - tarsus2_T1_right
    - tarsus3_T1_right
    - tarsus4_T1_right
    - claw_T1_right
    - coxa_T2_left
    - femur_T2_left
    - tibia_T2_left
    - tarsus_T2_left
    - tarsus2_T2_left
    - tarsus3_T2_left
    - tarsus4_T2_left
    - claw_T2_left
    - coxa_T2_right
    - femur_T2_right
    - tibia_T2_right
    - tarsus_T2_right
    - tarsus2_T2_right
    - tarsus3_T2_right
    - tarsus4_T2_right
    - claw_T2_right
    - coxa_T3_left
    - femur_T3_left
    - tibia_T3_left
    - tarsus_T3_left
    - tarsus2_T3_left
    - tarsus3_T3_left
    - tarsus4_T3_left
    - claw_T3_left
    - coxa_T3_right
    - femur_T3_right
    - tibia_T3_right
    - tarsus_T3_right
    - tarsus2_T3_right
    - tarsus3_T3_right
    - tarsus4_T3_right
    - claw_T3_right
  joint_names:
    - coxa_flexion_T1_left
    - coxa_twist_T1_left
    - femur_twist_T1_left
    - femur_T1_left
    - tibia_T1_left
    - tarsus_T1_left
    - coxa_flexion_T1_right
    - coxa_twist_T1_right
    - femur_twist_T1_right
    - femur_T1_right
    - tibia_T1_right
    - tarsus_T1_right
    - coxa_flexion_T2_left
    - coxa_twist_T2_left
    - femur_twist_T2_left
    - femur_T2_left
    - tibia_T2_left
    - tarsus_T2_left
    - coxa_flexion_T2_right
    - coxa_twist_T2_right
    - femur_twist_T2_right
    - femur_T2_right
    - tibia_T2_right
    - tarsus_T2_right
    - coxa_flexion_T3_left
    - coxa_twist_T3_left
    - femur_twist_T3_left
    - femur_T3_left
    - tibia_T3_left
    - tarsus_T3_left
    - coxa_flexion_T3_right
    - coxa_twist_T3_right
    - femur_twist_T3_right
    - femur_T3_right
    - tibia_T3_right
    - tarsus_T3_right
  lower_leg_names:
    - tarsus_T1_left
    - tarsus_T1_right
    - tarsus_T2_left
    - tarsus_T2_right
    - tarsus_T3_left
    - tarsus_T3_right
